<?php

/**
 * FileMinifier.php - JS and CSS file minifier
 *
 * Minify the javascript or css code generated by the Jaxon library and plugins.
 *
 * @package jaxon-utils
 * @author Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @copyright 2022 Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause BSD 3-Clause License
 * @link https://github.com/jaxon-php/jaxon-core
 */

namespace Jaxon\Utils\File;

use JShrink\Minifier as JsMinifier;
use MatthiasMullie\Minify\CSS as CssMinifier;
use Exception;

use function file_get_contents;
use function file_put_contents;
use function in_array;
use function is_file;
use function pathinfo;
use function trim;

class FileMinifier
{
    /**
     * @var CssMinifier
     */
    private $xCssMinifier = null;

    /**
     * @return CssMinifier
     */
    private function css(): CssMinifier
    {
        return $this->xCssMinifier ?? $this->xCssMinifier = new CssMinifier();
    }

    /**
     * Minify javascript or css code
     *
     * @param string $sFile The javascript or cess file to be minified
     * @param string $sMinFile The minified javascript file
     *
     * @return bool
     */
    public function minify(string $sFile, string $sMinFile): bool
    {
        $sExtension = pathinfo($sFile, PATHINFO_EXTENSION);
        if(!in_array($sExtension, ['js', 'css']))
        {
            return false;
        }

        try
        {
            $sCode = file_get_contents($sFile);
            $sMinCode = trim($sExtension === 'js' ?
                JsMinifier::minify($sCode) :
                $this->css()->add($sCode)->minify());
            if($sMinCode === '')
            {
                return false;
            }

            file_put_contents($sMinFile, $sMinCode);

            return is_file($sMinFile);
        }
        catch(Exception $e)
        {
            return false;
        }
    }
}
